#!/bin/bash
# 수동 배포 명령어 (서버에서 실행)

# 이 스크립트의 명령어를 서버에 접속하여 실행하세요
# ssh metal@34.47.89.217

echo "🚀 수동 배포 명령어"
echo ""
echo "서버에 접속한 후 다음 명령어를 실행하세요:"
echo ""
echo "=========================================="
echo "# 1. 디렉토리 생성"
echo "mkdir -p /home/metal/energy-platform"
echo "cd /home/metal/energy-platform"
echo ""
echo "# 2. Git 설치 (필요시)"
echo "sudo apt-get update"
echo "sudo apt-get install -y git"
echo ""
echo "# 3. Git repository clone"
echo "git clone https://github.com/kimeastsky2019/Ontology_EnergyAgent_diaster.git ."
echo ""
echo "# 4. Python 설치 (필요시)"
echo "sudo apt-get install -y python3 python3-pip python3-venv"
echo ""
echo "# 5. Node.js 설치 (필요시)"
echo "curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -"
echo "sudo apt-get install -y nodejs"
echo ""
echo "# 6. 백엔드 설정"
echo "cd backend"
echo "python3 -m venv venv"
echo "source venv/bin/activate"
echo "pip install --upgrade pip"
echo "pip install -r requirements.txt"
echo ""
echo "# 7. 프론트엔드 설정"
echo "cd ../frontend"
echo "npm install"
echo ""
echo "# 8. 환경 변수 설정"
echo "cd ../backend"
echo "cp .env.example .env"
echo "nano .env  # 필요한 값 설정"
echo ""
echo "# 9. 서비스 실행"
echo "source venv/bin/activate"
echo "uvicorn src.main:app --host 0.0.0.0 --port 8000"
echo "=========================================="

