#!/bin/bash
# 서버에 GitHub SSH 키 설정 (서버에서 실행)

echo "🔐 GitHub SSH 키 설정 (서버에서 실행)"
echo ""
echo "이 스크립트는 서버에 SSH로 접속한 후 실행하세요:"
echo "  ssh gcp-energy"
echo "  bash <(curl -s ...)"
echo ""
echo "또는 수동으로:"
echo ""
echo "1. SSH 키 생성:"
echo "   ssh-keygen -t ed25519 -C \"metal@energy-platform\" -f ~/.ssh/github_key"
echo ""
echo "2. 공개 키 확인:"
echo "   cat ~/.ssh/github_key.pub"
echo ""
echo "3. GitHub에 SSH 키 추가:"
echo "   - GitHub → Settings → SSH and GPG keys"
echo "   - New SSH key 클릭"
echo "   - 위의 공개 키 붙여넣기"
echo ""
echo "4. SSH config 설정 (~/.ssh/config):"
echo "   Host github.com"
echo "       HostName github.com"
echo "       User git"
echo "       IdentityFile ~/.ssh/github_key"
echo "       StrictHostKeyChecking no"
echo ""
echo "5. 연결 테스트:"
echo "   ssh -T git@github.com"

